### ISSUE TITLE
$ firebase deploy --only functions === Error

### ISSUE THREAD

**Issue by capacitivellc** [VirgilSecurity/demo-firebase-func#11]
Last step of Readme results in the following error.

```
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

Error: Illegal arguments for function privateKeyToDER.
    at Function.privateKeyToDERSafe (/Users/aricbrown/Documents/GitHub/demo-firebase-func/functions/node_modules/virgil-crypto/dist/virgil-crypto.cjs.js:223:32)
    at Object.privateKeyToDer (/Users/aricbrown/Documents/GitHub/demo-firebase-func/functions/node_modules/virgil-crypto/dist/virgil-crypto.cjs.js:411:41)
    at VirgilCrypto.importPrivateKey (/Users/aricbrown/Documents/GitHub/demo-firebase-func/functions/node_modules/virgil-crypto/dist/virgil-crypto.cjs.js:1292:43)
    at Object.<anonymous> (/Users/aricbrown/Documents/GitHub/demo-firebase-func/functions/lib/index.js:34:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
```

**Comment by xlwknx** [comment]
This repository is no longer maintained.

For firebase and virgil backend integrations please use: 
https://github.com/VirgilSecurity/virgil-e3kit-firebase-func

Here you can find list of all actual guides and demo applications:
https://github.com/VirgilSecurity/awesome-virgil
